---
title: "Likeliness to Recommend to a Friend or Colleague"
output:
  rmdformats::robobook:
    self_contained: true # Other options are downcute, material, readthedown, html_clean, html_docco, lockdown, https://github.com/juba/rmdformats
    thumbnails: false
    lightbox: true
    gallery: false
    highlight: kate # Also can do tango
    number_sections: false
    includes:
      after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, 
                      message = F, 
                      warning = F, 
                      fig.align = 'center', 
                      cache = F, 
                      tidy = T) # No messages, warnings, code echo, align figures center, cache images, and tidy
library(tidyverse) # So you don't have to code in base R
library(readr) # Reading in rds
library(here) # Cross network consistency
library(scales) # For graphing scales
library(ggrepel) # For text output on graphs
library(gt) # For tables
library(lubridate) # For dates
library(ggiraph) # For interactivity
teaching_colors <- c("#04ABEB", "#040404", "#346475", "#324D56") # Teaching Lab Color Palette - derived from logo
col = grDevices::colorRampPalette(c("#040404", "#04ABEB")) # Color palette maker for blue theme, based on teaching lab color palette
htmltools::tagList(rmarkdown::html_dependency_font_awesome()) # Needed so fa's in footer will show

teaching_lab_df <- read_rds(here("Data/original_df.rds")) # Read original data for column names

# There's Guidebooks, and GuideBooks so vector for later filter
guidebooks <- c("Guidebooks|GuideBooks")

not_state_level <- c("EL|IM|Guidebooks|GuideBooks") # Define those for which we should filter for later
```

```{r}
theme_tl <- function(){
  
  font <- "Oswald" # Assign font up front
  
  theme_minimal() %+replace%
  theme(legend.position = c(0.95,1),
          legend.title = element_blank(),
          plot.title = element_text(hjust = 0.5, font),
          plot.subtitle = element_text(hjust = 0.5, font),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          axis.text.x = element_text(color = "#324D56", font,
                                     margin = unit(c(0, 0, -0.3, 0), "cm"), vjust = 28),
          axis.title.y = element_text(font),
          axis.text.y = element_text(color= "#324D56", font),
          legend.text = element_text(font),
          plot.caption = element_text(font, vjust = 25, hjust = 0.2),
          plot.margin = unit(c(0.1,0.1,-0.8,0.1), "cm"))
}
```


# Comparing Pre-and Post Pandemic Scores


## All Scores by Date

Let's make this all scores including factors.

```{r}
grouped_teaching_df <- teaching_lab_df %>%
  dplyr::group_by(`Date for the session`) %>%
  dplyr::mutate(count = length(`Professional training session`),
           score = sum(`How likely are you to recommend this professional learning to a colleague or friend?`, na.rm = T)/count,
           prepost = case_when(`Date for the session` >= as.Date("2020-04-01") ~ "Post-Pandemic Average: 7.67",
                               `Date for the session` < as.Date("2020-04-01") ~ "Pre-Pandemic Average: 8.48")) %>%
  dplyr::group_by(prepost) %>%
  dplyr::mutate(mean_score = mean(score, na.rm = T)) %>%
  dplyr::ungroup() %>%
  dplyr::distinct(`Date for the session`, .keep_all = T) %>%
  dplyr::arrange(score) %>%# Arrange for plotting
  drop_na(`Date for the session`) %>%
  mutate(grouping = case_when(str_detect(`Professional training session`, "EL") == T ~ "EL",
                              str_detect(`Professional training session`, guidebooks) == T ~ "Guidebooks",
                              str_detect(`Professional training session`, "IM") == T ~ "IM",
                              !str_detect(`Professional training session`, not_state_level) == T ~ "State-Level"))
  
# Date x scale
ggplot(grouped_teaching_df, aes(x = `Date for the session`,
                                y = score, 
                                fill = factor(prepost, levels = c("Pre-Pandemic Average: 8.48", "Post-Pandemic Average: 7.67")),
                                color = factor(prepost, levels = c("Pre-Pandemic Average: 8.48", "Post-Pandemic Average: 7.67")),
                                # alpha = factor(grouping, levels = c("Guidebooks", "EL", "IM", "State-Level"))
                                    )) +
  geom_col() +
    geom_hline(color = "black", yintercept = 0) +
  labs(x = "", y = "Average Score per Session", title = "Likeliness to Recommend to a Friend or Colleague Before and After the Pandemic") +
    scale_fill_manual(values = c("#04ABEB", "#324D56")) +
    scale_color_manual(values = c("#04ABEB", "#324D56")) +
    scale_y_continuous(limits = c(-0.4, 10), breaks = scales::breaks_pretty(n = 10)) +
    scale_x_date(breaks = scales::breaks_pretty(n = 20)) +
    theme(legend.position = c(0.95,1),
          legend.title = element_blank(),
          plot.title = element_text(hjust = 0.5, family = "Oswald"),
          plot.subtitle = element_text(hjust = 0.5, family = "Oswald"),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          axis.text.x = element_text(color = "#324D56", family = "Oswald",
                                     margin = unit(c(0, 0, -0.3, 0), "cm"), vjust = 13),
          axis.title.y = element_text(family = "Oswald"),
          axis.text.y = element_text(color= "#324D56", family = "Oswald"),
          legend.text = element_text(family = "Oswald"),
          plot.caption = element_text(family = "Oswald", vjust = 25, hjust = 0.2),
          plot.margin = unit(c(0.1,-0.6,-0.8,0.1), "cm"))

ggsave(here("Images/PresentationAllScoresDate.png"), width = 16, height = 9)

# Factored x scale
grouped_teaching_df %>% filter(score != 0) %>%
  ggplot(aes(x = factor(`Date for the session`),
                                y = score, 
                                fill = factor(prepost, levels = c("Pre-Pandemic Average: 8.48", "Post-Pandemic Average: 7.67")),
                                # alpha = factor(grouping, levels = c("Guidebooks", "EL", "IM", "State-Level"))
                                    )) +
    geom_col(color = "black") +
    geom_segment(aes(x = "2019-06-05", xend = "2020-01-05", y = -0.01, yend = -0.01),
                 arrow = grid::arrow(length = unit(0.3, "cm"),
                                     ends = "both",
                                     type = "open"), color = "gray80", size = 1.5) +
    geom_segment(aes(x = "2020-01-05", xend = "2020-12-05", y = -0.01, yend = -0.01),
                 arrow = grid::arrow(length = unit(0.3, "cm"),
                                     ends = "both",
                                     type = "open"), color = "gray5", size = 1.5) +
    # geom_segment(aes(x = "2019-08-24", xend = "2019-06-24", y = -0.4, yend = -0.01),
    #              arrow = grid::arrow(length = unit(0.07, "in"),
    #                                                    ends = "last"), color = "gray20", size = 1.5) +
    # geom_segment(aes(x = "2019-08-24", xend = "2019-09-25", y = -0.4, yend = -0.01),
    #              arrow = grid::arrow(length = unit(0.07, "in"),
    #                                                    ends = "last"), color = "gray20", size = 1.5) +
    # geom_segment(aes(x = "2019-08-24", xend = "2019-11-06", y = -0.4, yend = -0.01),
    #              arrow = grid::arrow(length = unit(0.07, "in"),
    #                                                    ends = "last"), color = "gray20", size = 1.5) +
    geom_text(aes(x = "2019-09-24", y = -0.15, label = "2019"), color = "gray80", size = 8, family = "Oswald") +
    geom_text(aes(x = "2020-03-02", y = -0.15, label = "2020"), color = "gray5", size = 8, family = "Oswald") +
  labs(x = "", y = "Average Score per Session",
       title = "Likeliness to Recommend to a Friend or Colleague Before and After the Pandemic") +
    scale_fill_manual(values = c("#04ABEB", "#324D56")) +
    scale_color_manual(values = c("#04ABEB", "#324D56")) +
    scale_y_continuous(limits = c(-0.4, 10), breaks = scales::breaks_pretty(n = 10)) +
    scale_x_discrete() +
    theme(legend.position = c(0.95,1),
          legend.title = element_blank(),
          plot.title = element_text(hjust = 0.5, family = "Oswald", size = 18),
          plot.subtitle = element_text(hjust = 0.5, family = "Oswald"),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          axis.text.x = element_blank(),
          axis.title.y = element_text(family = "Oswald", size = 13),
          axis.text.y = element_text(color= "#324D56", family = "Oswald", size = 11),
          legend.text = element_text(family = "Oswald", size = 12),
          # plot.caption = element_text(family = "Oswald", vjust = 15, hjust = 0.1),
          plot.margin = unit(c(0.1,0.1,-2.5,0.1), "cm"))
ggsave(here("Images/PresentationAllScoresFactor.png"), width = 2200/300*3.5, height = 1250/300*3.5)
```


## EL

```{r}
# Group and then score the data, filter for the pertinent group
grouped_teaching_EL <- teaching_lab_df %>%
  dplyr::filter(str_detect(`Professional training session`, "EL") == T) %>% # Filter for just EL
  dplyr::group_by(`Date for the session`) %>%
  dplyr::mutate(count = length(`Professional training session`),
           score = sum(`How likely are you to recommend this professional learning to a colleague or friend?`)/count,
           prepost = case_when(`Date for the session` >= as.Date("2020-04-01") ~ "Post-Pandemic",
                               `Date for the session` < as.Date("2020-04-01") ~ "Pre-Pandemic")) %>%
  dplyr::group_by(prepost) %>%
  dplyr::mutate(mean_score = mean(score, na.rm = T)) %>%
  dplyr::ungroup() %>%
  dplyr::distinct(`Date for the session`, .keep_all = T) %>%
  dplyr::arrange(score) # Arrange for plotting

## Plot by pre and post pandemic by EL training sessions dates.
ggplot(grouped_teaching_EL, aes(x = fct_reorder(as.factor(format(`Date for the session`, '%b %d,\n%Y')), `Date for the session`),
                                y = score, 
                                fill = factor(prepost, levels = c("Pre-Pandemic", "Post-Pandemic")),
                                color = factor(prepost, levels = c("Pre-Pandemic", "Post-Pandemic"))
                                    )) +
  geom_col(color = ifelse(grouped_teaching_EL$prepost == "Pre-Pandemic", "#324D56", "black")) +
  labs(x = "", y = "Average Score per Session", title = "EL Virtual Bootcamp Scores Before and After the Pandemic") +
    scale_fill_manual(values = c("#04ABEB", "#324D56")) +
    scale_color_manual(values = c("#04ABEB", "#324D56")) +
    scale_y_continuous(limits = c(-0.4, 10), breaks = scales::breaks_pretty(n = 10)) +
    theme(legend.position = c(0.95,1),
          legend.title = element_blank(),
          plot.title = element_text(hjust = 0.5, family = "Oswald"),
          plot.subtitle = element_text(hjust = 0.5, family = "Oswald"),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          axis.text.x = element_text(color = "#324D56", family = "Oswald",
                                     margin = unit(c(0, 0, -0.3, 0), "cm"), vjust = 28),
          axis.title.y = element_text(family = "Oswald"),
          axis.text.y = element_text(color= "#324D56", family = "Oswald"),
          legend.text = element_text(family = "Oswald"),
          plot.caption = element_text(family = "Oswald", vjust = 25, hjust = 0.2),
          plot.margin = unit(c(0.1,0.1,-0.8,0.1), "cm"))
ggsave(here("Images/PresentationELScores.png"), width = 14, height = 9)
```


## Guidebooks

```{r}
grouped_teaching_Guidebooks <- teaching_lab_df %>%
  dplyr::filter(str_detect(`Professional training session`, guidebooks) == T) %>% # Filter for just EL
  dplyr::group_by(`Date for the session`) %>%
  dplyr::mutate(count = length(`Professional training session`),
           score = sum(`How likely are you to recommend this professional learning to a colleague or friend?`, na.rm = T)/count,
           prepost = case_when(`Date for the session` >= as.Date("2020-04-01") ~ "Post-Pandemic",
                               `Date for the session` < as.Date("2020-04-01") ~ "Pre-Pandemic")) %>%
  dplyr::group_by(prepost) %>%
  dplyr::mutate(mean_score = mean(score, na.rm = T)) %>%
  dplyr::ungroup() %>%
  dplyr::distinct(`Date for the session`, .keep_all = T) %>%
  dplyr::arrange(score) # Arrange for plotting

# Which ones are NA?

na_dates <- teaching_lab_df %>% dplyr::filter(str_detect(`Professional training session`, guidebooks) == T,
                                  is.na(`How likely are you to recommend this professional learning to a colleague or friend?`)) %>%
    distinct(`Date for the session`)



na_results <- teaching_lab_df %>% dplyr::filter(na_dates$`Date for the session` == `Date for the session`) # Looks like its entirely as a result of Louisiana State Content Leader Training 

# Simply too many here to plot text
# bar_labels <- dput(grouped_teaching_Guidebooks$`Professional training session`)
# bar_labels <- str_replace_all(bar_labels, "GuideBooks", "Guidebooks")
# bar_labels <- str_replace_all(bar_labels, "Guidebooks ", "Guidebooks\n")

## Plot by pre and post pandemic by EL training sessions dates.
ggplot(grouped_teaching_Guidebooks, aes(x = fct_reorder(as.factor(`Date for the session`), `Date for the session`), y = score, 
                                        fill = factor(prepost, levels = c("Pre-Pandemic", "Post-Pandemic")),
                                    color = factor(prepost, levels = c("Pre-Pandemic", "Post-Pandemic"))
                                    )) +
    geom_col(color = ifelse(grouped_teaching_Guidebooks$prepost == "Pre-Pandemic", "#324D56", "black")) +
    geom_segment(aes(x = "2019-06-05", xend = "2019-12-19", y = -0.2, yend = -0.2),
                 arrow = grid::arrow(length = unit(0.3, "cm"),
                                                       ends = "both"), color = "gray80", size = 1.5) +
    geom_segment(aes(x = "2020-01-05", xend = "2020-12-04", y = -0.2, yend = -0.2),
                 arrow = grid::arrow(length = unit(0.3, "cm"),
                                                       ends = "both"), color = "gray20", size = 1.5) +
    geom_segment(aes(x = "2019-08-24", xend = "2019-06-24", y = -0.4, yend = -0.01),
                 arrow = grid::arrow(length = unit(0.07, "in"),
                                                       ends = "last"), color = "gray20", size = 1.5) +
    geom_segment(aes(x = "2019-08-24", xend = "2019-09-25", y = -0.4, yend = -0.01),
                 arrow = grid::arrow(length = unit(0.07, "in"),
                                                       ends = "last"), color = "gray20", size = 1.5) +
    geom_segment(aes(x = "2019-08-24", xend = "2019-11-06", y = -0.4, yend = -0.01),
                 arrow = grid::arrow(length = unit(0.07, "in"),
                                                       ends = "last"), color = "gray20", size = 1.5) +
    geom_text(aes(x = "2019-09-19", y = -0.4, label = "2019"), color = "gray80") +
    geom_text(aes(x = "2020-03-02", y = -0.4, label = "2020"), color = "gray20") +
    labs(x = "", y = "Average Score per Session", title = "Guidebooks' Scores Before and After the Pandemic",
         caption = "Lafayette School District did not include any scores for several sessions") +
    scale_fill_manual(values = c("#04ABEB", "#324D56")) +
    scale_color_manual(values = c("#04ABEB", "#324D56")) +
    scale_y_continuous(limits = c(-0.4, 10), breaks = scales::breaks_pretty(n = 10)) +
    scale_x_discrete() +
    theme(legend.position = c(0.95,1),
          legend.title = element_blank(),
          plot.title = element_text(hjust = 0.5, family = "Oswald"),
          plot.subtitle = element_text(hjust = 0.5, family = "Oswald"),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          # axis.text.x = element_text(color = "#324D56", family = "Oswald",
          #                            margin = unit(c(0, 0, -0.3, 0), "cm"),
          #                            angle = 90),
          axis.text.x = element_blank(),
          axis.title.y = element_text(family = "Oswald"),
          axis.text.y = element_text(color= "#324D56", family = "Oswald"),
          legend.text = element_text(family = "Oswald"),
          plot.caption = element_text(family = "Oswald", vjust = 25, hjust = 0.2),
          plot.margin = unit(c(0.1,0.1,-0.8,0.1), "cm"))
ggsave(here("Images/PresentationGuidebooksScores.png"), width = 14, height = 9)
```


## Illustrative Mathematics (IM)

```{r}
grouped_teaching_IM <- teaching_lab_df %>%
  dplyr::filter(str_detect(`Professional training session`, "IM") == T) %>% # Filter for just EL
  dplyr::group_by(`Date for the session`) %>%
  dplyr::mutate(count = length(`Professional training session`),
           score = sum(`How likely are you to recommend this professional learning to a colleague or friend?`)/count,
           prepost = case_when(`Date for the session` >= as.Date("2020-03-23") ~ "Post-Pandemic",
                               `Date for the session` < as.Date("2020-03-23") ~ "Pre-Pandemic")) %>%
  dplyr::group_by(prepost) %>%
  dplyr::mutate(mean_score = mean(score, na.rm = T)) %>%
  dplyr::ungroup() %>%
  dplyr::distinct(`Date for the session`, .keep_all = T) %>%
  dplyr::arrange(score) # Arrange for plotting

bar_labels <- dput(grouped_teaching_IM$`Professional training session`)
bar_labels <- str_replace_all(bar_labels, "IM", "")
bar_labels <- str_replace_all(bar_labels, "Day", "")
bar_labels <- str_replace_all(bar_labels, "[:digit:]", "")
bar_labels <- str_replace_all(bar_labels, ":", "")
bar_labels <- str_replace_all(bar_labels, ",", "")
bar_labels <- str_replace_all(bar_labels, "(Bootcamp).*", "\\1")
bar_labels <- str_replace_all(bar_labels, "(School Leaders).*", "\\1")
bar_labels <- str_remove(bar_labels, "Springfield EZ")
bar_labels[1] <-"Nebraska Virtual Series"
bar_labels <- str_trim(bar_labels, side = c("both"))
bar_labels <- str_replace_all(bar_labels, " ", "\n")
bar_labels <- str_replace_all(bar_labels, "BootCamp", "Bootcamp")

## Plot by pre and post pandemic by EL training sessions dates.
ggplot(grouped_teaching_IM, aes(x = fct_reorder(as.factor(format(`Date for the session`, '%b %d,\n%Y')), `Date for the session`), 
                                y = score, 
                                fill = factor(prepost, levels = c("Pre-Pandemic", "Post-Pandemic")))) +
    geom_col(color = ifelse(grouped_teaching_IM$prepost == "Pre-Pandemic", "#324D56", "black")) +
    geom_text(aes(label = bar_labels),
              color = "#324D56",
              position = position_dodge(0.9),
              vjust = -0.25,
              lineheight = 0.8,
              size = 2.5,
              family = "Oswald") +
    labs(x = "", y = "Average Score per Session", title = "Illustrative Mathematic's Scores Before and After the Pandemic") +
    scale_fill_manual(values = c("#04ABEB", "#324D56")) +
    scale_color_manual(values = c("#04ABEB", "#324D56")) +
    scale_y_continuous(limits = c(0, 10), breaks = scales::breaks_pretty(n = 10)) +
  #   geom_segment(aes(x = "July 09, 2019", xend = "December 12, 2020", y = -0.2, yend = -0.2),
  #                arrow = grid::arrow(length = unit(0.3, "cm"),
  #                                                      ends = "both"), color = "#04ABEB", size = 1.5) +
  # geom_segment(aes(x = "January 06, 2020", xend = "October 20, 2020", y = -0.2, yend = -0.2),
  #                arrow = grid::arrow(length = unit(0.3, "cm"),
  #                                                      ends = "both"), color = "#324D56", size = 1.5) +
    theme(legend.position = c(0.86, 0.99),
          legend.box.margin = margin(c(-10,-10,-10,-10)),
          legend.title = element_blank(),
          plot.title = element_text(hjust = 0.5, family = "Oswald"),
          plot.subtitle = element_text(hjust = 0.5, family = "Oswald"),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          axis.text.x = element_text(color = "#324D56", family = "Oswald",
                                     margin = unit(c(0, 0, -1, 0), "cm"),
                                     vjust = 19),
          # axis.text.x = element_blank(),
          axis.text.y = element_text(color = "#324D56", family = "Oswald"),
          axis.title.y = element_text(family = "Oswald"),
          legend.text = element_text(family = "Oswald"))
ggsave(here("Images/PresentationIMScores.png"), width = 14, height = 9)
```


## State-level work

```{r}
grouped_teaching_SL <- teaching_lab_df %>%
  dplyr::filter(!str_detect(`Professional training session`, not_state_level) == T) %>% # Filter for just EL
  dplyr::group_by(`Date for the session`) %>%
  dplyr::mutate(count = length(`Professional training session`),
           score = sum(`How likely are you to recommend this professional learning to a colleague or friend?`)/count,
           prepost = case_when(`Date for the session` >= as.Date("2020-03-23") ~ "Post-Pandemic",
                               `Date for the session` < as.Date("2020-03-23") ~ "Pre-Pandemic")) %>%
  dplyr::group_by(prepost) %>%
  dplyr::mutate(mean_score = mean(score, na.rm = T)) %>%
  dplyr::ungroup() %>%
  dplyr::distinct(`Date for the session`, .keep_all = T) %>%
  dplyr::arrange(score) # Arrange for plotting

bar_labels <- grouped_teaching_SL$`Professional training session`
# gsub("((\\S+\\s){2})","\\1\n ", bar_labels) # Doesn't interact well with ggplot
bar_labels <- c("General: Math", "Innovation Network\nFellowship Meeting 1", 
"Innovation Network\nFellowship Meeting\n4 Day 2", "General: Math", 
"Innovation Network\nFellowship Meeting 2", "General: Math", 
"School Leaders:\nLafayette SL-3", "Innovation Network\nFellowship, Meeting 2", 
"Innovation Network\nFellowship Meeting\n4 Day 1", "School Leaders:\nLafayette SL-3", 
"General: Math", "School Leaders:\nLafayette SL-4")

facilitators <- grouped_teaching_SL %>% select(`Select the name of your first facilitator.`,
                                               `Select the name of your second facilitator.`)
## Plot by pre and post pandemic by EL training sessions dates.
ggplot(grouped_teaching_SL, aes(x = fct_reorder(as.factor(format(`Date for the session`, '%b %d, %Y')), `Date for the session`), 
                                y = score)) +
  geom_col(fill = "#04ABEB", color = "#324D56") +
  geom_text(aes(label = bar_labels),
            color = "#324D56",
            position = position_dodge(0.9),
            vjust = -0.25,
            size = 2.8,
            family = "Oswald") +
  labs(x = "", y = "Average Score per Session", title = "State Level Scores", subtitle = "Exclusively prior to the pandemic") +
  scale_y_continuous(limits = c(0, 10), breaks = scales::breaks_pretty(n = 10)) +
  scale_x_discrete() +
  theme(legend.position = "none",
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5, family = "Oswald"),
        plot.subtitle = element_text(hjust = 0.5, family = "Oswald"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.title.y = element_text(family = "Oswald"),
        axis.text.x = element_text(color = "#324D56", family = "Oswald", 
                                   margin = unit(c(0, 0, -0.2, 0), "cm"),
                                   vjust = 10),
        axis.text.y = element_text(color= "#324D56", family = "Oswald"))
ggsave(here("Images/PresentationStateLevelScores.png"), height = 2481/300, width = 3324/300, dpi = 300) # Triple zoom size with 300 dpi for best res
```


## Boxplot of All Scores

```{r}
# Add columns for pre and post pandemic, as well as different types of training sessions
sorted_teaching_df <- teaching_lab_df %>%
  group_by(`Date for the session`) %>%
  mutate(pro_grouping = case_when(!str_detect(`Professional training session`, not_state_level) == T ~ "State-Level",
                                  str_detect(`Professional training session`, "IM") == T ~ "Illustrative Mathematics",
                                  str_detect(`Professional training session`, guidebooks) == T ~ "Guidebooks",
                                  str_detect(`Professional training session`, "EL") == T ~ "EL"),
         prepost = case_when(`Date for the session` >= as.Date("2020-03-23") ~ "Post-Pandemic",
                               `Date for the session` < as.Date("2020-03-23") ~ "Pre-Pandemic")) %>%
  drop_na(`How likely are you to recommend this professional learning to a colleague or friend?`,
          pro_grouping) %>%
  group_by(pro_grouping, prepost) %>%
  # Means before and after pandemic by type of training session
  mutate(grouped_means = mean(`How likely are you to recommend this professional learning to a colleague or friend?`, na.rm = T)) %>%
  mutate(pro_grouping = forcats::fct_reorder(pro_grouping, -grouped_means)) %>%
  ungroup() %>%
  group_by(prepost) %>%
  # Means of before and after pandemic
  mutate(mean_score = mean(`How likely are you to recommend this professional learning to a colleague or friend?`)) %>%
  ungroup()

# Axis colors 
axis_colors <- rev(c("#040404", "#324D56", "#346475", "#04ABEB"))

# Make the graph aesthetics, theme, and limits
g <- ggplot(sorted_teaching_df, aes(
              x = fct_rev(pro_grouping), 
              y = `How likely are you to recommend this professional learning to a colleague or friend?`, 
              color = pro_grouping
  )) +
  scale_y_continuous(limits = c(0, 10), breaks = scales::breaks_pretty(n = 10)) +
  scale_color_manual(values = col(4)) +
  facet_wrap( ~ factor(prepost, levels = c("Pre-Pandemic", "Post-Pandemic")), ncol = 1) +
  coord_flip() +
  labs(x = "", y = "Likeliness to Recommend to a Friend or Colleague", title = "Comparing Scores Before and After the Pandemic") +
  theme(legend.position = "none",
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5, family = "Oswald"),
        plot.subtitle = element_text(hjust = 0.5, family = "Oswald"),
        panel.grid = element_blank(),
        axis.title.y = element_text(family = "Oswald"),
        axis.title.x = element_text(family = "Oswald"),
        axis.text.x = element_text(color = "#324D56", family = "Oswald", 
                                   margin = unit(c(0, 0, -0.2, 0), "cm"),
                                   vjust = 10),
        axis.text.y = element_text(color= axis_colors, family = "Oswald"),
        strip.text = element_text(family = "Oswald", size = 10),
        legend.text = element_text(family = "Oswald"),
        axis.ticks.x = element_line(size = 3, color = "#324D56", linetype = 2),
        axis.ticks.length.x = unit(0.2, "cm"))


# Graph with geoms applied for baselayer test
g + 
  geom_segment(
    aes(x = fct_rev(pro_grouping), xend = fct_rev(pro_grouping),
        y = mean_score, yend = grouped_means),
    show.legend = F,
    size = 0.8
  ) +
  geom_jitter(size = 3, height = 0.15) +
  stat_summary(fun = mean, geom = "point", size = 5) +
  geom_hline(aes(yintercept = mean_score), color = "gray70")

# State Label
state_label <- tibble(prepost = factor(c("Post-Pandemic")), 
                   label = c("No State-Level work has been done since the pandemic began."),
                   pro_grouping = "State-Level", 
                   `How likely are you to recommend this professional learning to a colleague or friend?` = 5)

# Illustrative Mathematics Label
illustrative_label <- tibble(prepost = factor(c("Post-Pandemic")), 
                   label = c("Only 3 Illustrative Mathematics professional learning session reviews\nhave been submitted in the post-pandemic era to yield this average."),
                   pro_grouping = "Illustrative Mathematics", 
                   `How likely are you to recommend this professional learning to a colleague or friend?` = 3.5)
illustrative_arrow <- tibble(prepost = factor(c("Post-Pandemic")),
                             pro_grouping = "Illustrative Mathematics",
                             xend = 2, # Arrow end for x axis, factor based
                             `How likely are you to recommend this professional learning to a colleague or friend?` = 3.5, # Arrow start for x axis
                             yend = 4.6) # Arrow end for y axis

# Guidebooks Label
guidebooks_label <- tibble(prepost = factor(c("Post-Pandemic")), 
                   label = c(glue::glue("Guidebooks scores remain strong,\nfalling only {round(sorted_teaching_df %>% dplyr::filter(pro_grouping == 'Guidebooks') %>% distinct(grouped_means) %>% summarise(grouped_means[1]-grouped_means[2]), 2)} on average.")),
                   pro_grouping = "Illustrative Mathematics", 
                   `How likely are you to recommend this professional learning to a colleague or friend?` = 9)
guidebooks_arrow <- tibble(prepost = factor(c("Post-Pandemic")),
                             pro_grouping = "Illustrative Mathematics",
                             xend = 3,
                             `How likely are you to recommend this professional learning to a colleague or friend?` = 9,
                             yend = 8.45)

# EL Label
el_label <- tibble(prepost = factor(c("Pre-Pandemic")), 
                   label = c(glue::glue("EL had the highest Pre-Pandemic scores,\nwith an average of {round(sorted_teaching_df %>% dplyr::filter(grouped_means == max(grouped_means)) %>% distinct(grouped_means), 2)}.")),
                   pro_grouping = "EL", 
                   `How likely are you to recommend this professional learning to a colleague or friend?` = 9.31)
el_arrow <- tibble(prepost = factor(c("Pre-Pandemic")),
                             pro_grouping = "EL",
                             xend = 4,
                             `How likely are you to recommend this professional learning to a colleague or friend?` = 9.5,
                             yend = 9.25)

average_label <- tibble(prepost = factor(c("Pre-Pandemic", "Post-Pandemic")), 
                   label = c(glue::glue("Pre-Pandemic average: {round(sorted_teaching_df %>% distinct(mean_score) %>% dplyr::filter(mean_score == max(mean_score)), 2)}"),
                             glue::glue("Post-Pandemic average: {round(sorted_teaching_df %>% distinct(mean_score) %>% dplyr::filter(mean_score == min(mean_score)), 2)}")),
                   pro_grouping = "Illustrative Mathematics", 
                   `How likely are you to recommend this professional learning to a colleague or friend?` = c(9.6, 8.4))
average_arrow <- tibble(prepost = factor(c("Pre-Pandemic", "Post-Pandemic")), 
                   pro_grouping = "Illustrative Mathematics", 
                   `How likely are you to recommend this professional learning to a colleague or friend?` = c(9.15, 7.92),
                   yend = c(8.95, 7.68),
                   xend = c(1.55,1.55))

# Graph with text annotations
(g_text <- 
  g + 
  geom_segment(
    aes(x = fct_rev(pro_grouping), xend = fct_rev(pro_grouping),
        y = mean_score, yend = grouped_means),
    show.legend = F,
    size = 0.8
  ) +
  geom_jitter_interactive(size = 3, aes(alpha = prepost,
                            tooltip = paste(`Select your site (district, parish, or network).`, 
                                            `Select the best description for your role.`,
                                            `What could have improved your experience?`,
                                            sep = "\n")), 
              height = 0.15, width = 0.28) + # Height changes width here since coord_flip already happened
  scale_alpha_manual(values = c(0.6, 0.2)) + # Manually change the alpha since they need to be set for different n
  stat_summary(fun = mean, geom = "point", size = 5) + # Add mean summary point
  geom_hline(aes(yintercept = mean_score), color = "gray70") +
  geom_text(data = state_label, aes(label = label), family = "Oswald", color = "gray20", size = 3) +
  geom_text(data = illustrative_label, aes(label = label), family = "Oswald", color = "gray20", size = 3, vjust = 1) +
  geom_text(data = guidebooks_label, aes(label = label), family = "Oswald", color = "gray20", size = 3, vjust = -1.1) +
  geom_text(data = el_label, aes(label = label), family = "Oswald", color = "gray20", size = 3, vjust = 2.5) +
  geom_text(data = average_label, aes(label = label), family = "Oswald", color = "gray20", size = 3, vjust = 5.5))

# Graph with arrow annotations
(g_arrow <- 
    g_text +
    geom_curve(data = illustrative_arrow, 
             arrow = arrow(length = unit(0.07, "inch")), 
             aes(xend = xend, yend = yend, x = 2.1),
             size = 0.4,
             color = "gray20",
             curvature = -0.3) +
    geom_curve(data = guidebooks_arrow, 
             arrow = arrow(length = unit(0.07, "inch")), 
             aes(xend = xend, yend = yend, x = 2.6),
             size = 0.4,
             color = "gray20",
             curvature = 0.3) +
    geom_curve(data = el_arrow, 
             arrow = arrow(length = unit(0.07, "inch")), 
             aes(xend = xend, yend = yend, x = 3.7),
             size = 0.4,
             color = "gray20",
             curvature = 0.4) +
    geom_curve(data = average_arrow, 
             arrow = arrow(length = unit(0.07, "inch")), 
             aes(xend = xend, yend = yend, x = c(1.55, 1.55)),
             size = 0.4,
             color = "gray70",
             curvature = 0))
tooltip_css <- "font-family:'Oswald';color:white;"
html_plot <- girafe(ggobj = g_arrow, fonts = list(sans = "Oswald"),
       options = list(opts_tooltip(offx = 15, offy = 15, use_cursor_pos = T, use_fill = T, css = tooltip_css),
                      opts_sizing(rescale = T),
                      opts_hover_inv(css = "opacity:0.1;"),
                      opts_toolbar(saveaspng = F)),
       width_svg = 16.833, height_svg = 10.0233
       ) %>%# Real size
  girafe_options(.,
                 htmlwidgets::sizingPolicy(padding = "0px",
                                           defaultWidth = "90%", defaultHeight = "90%"))
htmlwidgets::saveWidget(html_plot, file=here("Images/PresentationInteractive.html"))
ggsave(here("Images/PresentationPandemicScores.png"), width = 5050.179/300, height = 3007/300, dpi = 300)
```

## Table of responses

```{r}
# moretime <- c("More time to engage in discussion- not so heavy on the facilitator speaking and engaging everyone. Reflections & small group tasks would be helpful.",
#               "slowing down and more time to work within my grade level and talk with those teachers",
#               "A bit more time experiencing some of the activities that students will participate in.",
#               "more time with resources",
#               "Having more time to collaborate with fellow teachers.",
#               "More time to talk to grade level teachers",
#               "Probably more time to dive in and an in person training but unfortunately we didn't have either of those opportunities",
#               "more collaborations with our own school...",
#               "More chance to collaborate with same grade-level teachers. More opportunity to investigate the material with classroom teachers and formulate questions that would need answering.")
# moretime <- dput(sorted_teaching_df %>% dplyr::filter(str_detect(`What could have improved your experience?`,
#                                                 c("more time|More time|collaborat")) == T & 
#                                        `Date for the session` > "2020-04-01") %>%
#   dplyr::select() %>%
#     dplyr::pull())
# one_moretime <- moretime[1]
# one_moretime2 <- moretime[2]
# one_moretime3 <- moretime[3]
# one_moretime4 <- moretime[4]
# one_moretime5 <- moretime[5]
# one_moretime6 <- moretime[6]
# one_moretime7 <- moretime[7]
# one_moretime8 <- moretime[7]
# one_moretime9 <- moretime[9]
# one_moretime10 <- moretime[10]

post_responses <- sorted_teaching_df %>% 
  dplyr::filter(prepost == "Post-Pandemic") %>% 
  select(`How likely are you to recommend this professional learning to a colleague or friend?`, 
         `Why did you choose this rating?`, 
         `What could have improved your experience?`,
         `Professional training session`,
         `Date for the session`,
         `Select the name of your first facilitator.`) %>% 
  drop_na(`How likely are you to recommend this professional learning to a colleague or friend?`) %>%
  mutate(Date = format(`Date for the session`, '%b, %d %Y')) %>%
  select(-`Date for the session`) %>%
  dplyr::arrange(`How likely are you to recommend this professional learning to a colleague or friend?`)

pandemic_response_table <- post_responses %>%
  gt::gt() %>%
  tab_header(
    title = md("&#129440; **Reviews in the Post-Pandemic Era** &#129440;"),
    subtitle = md("Sorted *Worst-Best:* All 123 Responses")
  ) %>%
  cols_width(
    vars(`How likely are you to recommend this professional learning to a colleague or friend?`) ~ px(110),
         everything() ~ px(250)
  ) %>%
  cols_label(
    `How likely are you to recommend this professional learning to a colleague or friend?` = md("**Likeliness to Recommend**"),
    `Why did you choose this rating?` = md("**Why did you choose this rating?**"), 
    `What could have improved your experience?` = md("**What could have improved your experience?**"),
    `Professional training session` = md("**Professional training session**"),
    Date = md("**Date**"),
    `Select the name of your first facilitator.` = md("**Facilitator**")
  ) %>%
  cols_align(
    align = "center",
    columns = vars(`How likely are you to recommend this professional learning to a colleague or friend?`)
  ) %>%
  data_color(columns = vars(`How likely are you to recommend this professional learning to a colleague or friend?`),
             colors = scales::col_numeric(
               palette = col(nrow(post_responses))
               %>% as.character(),
             domain = NULL)
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "right",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_body(
        columns = vars(`How likely are you to recommend this professional learning to a colleague or friend?`)
      )
    )
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "bottom",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_column_labels(
        columns = gt::everything()
      )
    )
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "right",
        color = "gray50",
        weight = px(1.5)
      )
    ),
    locations = list(
      cells_body(
        columns = vars(`What could have improved your experience?`, `Why did you choose this rating?`, `Professional training session`)
      )
    )
  ) %>%
  # tab_style(
  #   style = list(
  #     cell_fill(color = "#043243")),
  #     locations = cells_body(
  #       columns = vars(`Why did you choose this rating?`, 
  #        `What could have improved your experience?`,
  #        `Professional training session`,
  #        `Date`,
  #        `Select the name of your first facilitator.`),
  #       rows = `What could have improved your experience?` == one_moretime
  #     )
  #   ) %>%
  # tab_style(
  #   style = list(
  #     cell_fill(color = "#043243")),
  #     locations = cells_body(
  #       columns = vars(`Why did you choose this rating?`, 
  #        `What could have improved your experience?`,
  #        `Professional training session`,
  #        `Date`,
  #        `Select the name of your first facilitator.`),
  #       rows = `What could have improved your experience?` == one_moretime2
  #     )
  #   ) %>%
  # tab_style(
  #   style = list(
  #     cell_fill(color = "#043243")),
  #     locations = cells_body(
  #       columns = vars(`Why did you choose this rating?`, 
  #        `What could have improved your experience?`,
  #        `Professional training session`,
  #        `Date`,
  #        `Select the name of your first facilitator.`),
  #       rows = `What could have improved your experience?` == one_moretime3
  #     )
  #   ) %>%
  # tab_style(
  #   style = list(
  #     cell_fill(color = "#043243")),
  #     locations = cells_body(
  #       columns = vars(`Why did you choose this rating?`, 
  #        `What could have improved your experience?`,
  #        `Professional training session`,
  #        `Date`,
  #        `Select the name of your first facilitator.`),
  #       rows = `What could have improved your experience?` == one_moretime4
  #     )
  #   ) %>%
  # tab_style(
  #   style = list(
  #     cell_fill(color = "#043243")),
  #     locations = cells_body(
  #       columns = vars(`Why did you choose this rating?`, 
  #        `What could have improved your experience?`,
  #        `Professional training session`,
  #        `Date`,
  #        `Select the name of your first facilitator.`),
  #       rows = `What could have improved your experience?` == one_moretime5
  #     )
  #   ) %>%
  # tab_style(
  #   style = list(
  #     cell_fill(color = "#043243")),
  #     locations = cells_body(
  #       columns = vars(`Why did you choose this rating?`, 
  #        `What could have improved your experience?`,
  #        `Professional training session`,
  #        `Date`,
  #        `Select the name of your first facilitator.`),
  #       rows = `What could have improved your experience?` == one_moretime6
  #     )
  #   ) %>%
  # tab_style(
  #   style = list(
  #     cell_fill(color = "#043243")),
  #     locations = cells_body(
  #       columns = vars(`Why did you choose this rating?`, 
  #        `What could have improved your experience?`,
  #        `Professional training session`,
  #        `Date`,
  #        `Select the name of your first facilitator.`),
  #       rows = `What could have improved your experience?` == one_moretime7
  #     )
  #   ) %>%
  # tab_style(
  #   style = list(
  #     cell_fill(color = "#043243")),
  #     locations = cells_body(
  #       columns = vars(`Why did you choose this rating?`, 
  #        `What could have improved your experience?`,
  #        `Professional training session`,
  #        `Date`,
  #        `Select the name of your first facilitator.`),
  #       rows = `What could have improved your experience?` == one_moretime8
  #     )
  #   ) %>%
  # tab_style(
  #   style = list(
  #     cell_fill(color = "#043243")),
  #     locations = cells_body(
  #       columns = vars(`Why did you choose this rating?`, 
  #        `What could have improved your experience?`,
  #        `Professional training session`,
  #        `Date`,
  #        `Select the name of your first facilitator.`),
  #       rows = `What could have improved your experience?` == one_moretime9
  #     )
  #   ) %>%
  # tab_style(
  #   style = list(
  #     cell_fill(color = "#043243")),
  #     locations = cells_body(
  #       columns = vars(`Why did you choose this rating?`, 
  #        `What could have improved your experience?`,
  #        `Professional training session`,
  #        `Date`,
  #        `Select the name of your first facilitator.`),
  #       rows = `What could have improved your experience?` == one_moretime10
  #     )
  #   ) %>%
  # tab_style(
  #   style = list(
  #     cell_fill(color = "#04ABEB")),
  #     locations = cells_body(
  #       columns = vars(`Why did you choose this rating?`, 
  #        `What could have improved your experience?`,
  #        `Professional training session`,
  #        `Date`,
  #        `Select the name of your first facilitator.`),
  #       rows = `Why did you choose this rating?` == moretime
  #     )
  #   ) %>%
  tab_options(
    summary_row.background.color = "#ACEACE80",
    grand_summary_row.background.color = "#990000",
    row_group.background.color = "#FFEFDB80",
    heading.background.color = "#04ABEB", # Main Heading Background
    column_labels.background.color = "#EFFBFC",
    stub.background.color = "#EFFBFC",
    table.font.color = "#323232",
    table.font.names = "Oswald",
    table_body.hlines.color = "#989898",
    table_body.border.top.color = "#989898",
    heading.border.bottom.color = "#989898",
    row_group.border.top.color = "#989898",
    row_group.border.bottom.style = "none",
    stub.border.style = "dashed",
    stub.border.color = "#989898",
    stub.border.width = "1px",
    summary_row.border.color = "#989898")
gtsave(pandemic_response_table, here("HTML/PresentationTable.html"))
```

```{r}
pandemic_response_table_filtered <- post_responses %>%
  dplyr::filter(str_detect(`What could have improved your experience?`, c("more time|More time|collaborat")) == T) %>%
  gt::gt() %>%
  tab_header(
    title = md("&#129440; **Reviews in the Post-Pandemic Era** &#129440;"),
    subtitle = md("Sorted *Worst-Best:* Filtered for Time and Collaboration")
  ) %>%
  cols_width(
    vars(`How likely are you to recommend this professional learning to a colleague or friend?`) ~ px(110),
         everything() ~ px(250)
  ) %>%
  cols_label(
    `How likely are you to recommend this professional learning to a colleague or friend?` = md("**Likeliness to Recommend**"),
    `Why did you choose this rating?` = md("**Why did you choose this rating?**"), 
    `What could have improved your experience?` = md("**What could have improved your experience?**"),
    `Professional training session` = md("**Professional training session**"),
    Date = md("**Date**"),
    `Select the name of your first facilitator.` = md("**Facilitator**")
  ) %>%
  cols_align(
    align = "center",
    columns = vars(`How likely are you to recommend this professional learning to a colleague or friend?`)
  ) %>%
  data_color(columns = vars(`How likely are you to recommend this professional learning to a colleague or friend?`),
             colors = scales::col_numeric(
               palette = col(nrow(post_responses))
               %>% as.character(),
             domain = NULL)
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "right",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_body(
        columns = vars(`How likely are you to recommend this professional learning to a colleague or friend?`)
      )
    )
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "bottom",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_column_labels(
        columns = gt::everything()
      )
    )
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "right",
        color = "gray50",
        weight = px(1.5)
      )
    ),
    locations = list(
      cells_body(
        columns = vars(`What could have improved your experience?`, `Why did you choose this rating?`, `Professional training session`)
      )
    )
  ) %>%
  tab_options(
    summary_row.background.color = "#ACEACE80",
    grand_summary_row.background.color = "#990000",
    row_group.background.color = "#FFEFDB80",
    heading.background.color = "#04ABEB", # Main Heading Background
    column_labels.background.color = "#EFFBFC",
    stub.background.color = "#EFFBFC",
    table.font.color = "#323232",
    table.font.names = "Oswald",
    table_body.hlines.color = "#989898",
    table_body.border.top.color = "#989898",
    heading.border.bottom.color = "#989898",
    row_group.border.top.color = "#989898",
    row_group.border.bottom.style = "none",
    stub.border.style = "dashed",
    stub.border.color = "#989898",
    stub.border.width = "1px",
    summary_row.border.color = "#989898")
gtsave(pandemic_response_table_filtered, here("HTML/PresentationTableFiltered.html"))
```


